services:
  localstack:
    build:
      context: ./00-localstack
      dockerfile: Dockerfile
    container_name: localstack-sqs
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    env_file:
      - ./00-localstack/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - rag-network

  opensearch:
    build: ./opensearch-db
    container_name: opensearch-node
    env_file:
      - ./opensearch-db/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - rag-network

  scraper:
    build: ./01-scraper
    container_name: scraper
    ports:
      - "8003:8003"
    env_file:
      - ./01-scraper/.env
    depends_on:
      localstack:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

  processor:
    build: ./02-processor
    container_name: processor
    env_file:
      - ./02-processor/.env
    depends_on:
      localstack:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

  embedder:
    build: ./03-embedder
    container_name: embedder
    ports:
      - "8001:8001"
    env_file:
      - ./03-embedder/.env
    depends_on:
      localstack:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

  inserter:
    build: ./04-inserter
    container_name: inserter
    env_file:
      - ./04-inserter/.env
    depends_on:
      localstack:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network

  api:
    build: ./api
    container_name: api
    ports:
      - "8010:8000"
    env_file:
      - ./api/.env
    depends_on:
      opensearch:
        condition: service_healthy
      embedder:
        condition: service_started
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  opensearch-data:
    driver: local
  django-data:
    driver: local

networks:
  rag-network:
    driver: bridge