services:
  s3-visualizer:
    build: .
    container_name: s3-visualizer
    stdin_open: true
    tty: true
    networks:
      - rag-network

networks:
  rag-network:
    external: true
    name: simpla_data_extraction_rag-network
