services:
  populate:
    build: .
    container_name: populate-norms
    command: [
      "--pg-host", "simpla_postgres",
      "--pg-port", "5432",
      "--pg-database", "simpla",
      "--pg-user", "postgres",
      "--pg-password", "postgres",
      "--api-url", "http://scraper:8003/process",
      "--delay", "5"
    ]
    networks:
      - simpla_data_extraction_rag-network
    profiles:
      - tools

networks:
  simpla_data_extraction_rag-network:
    external: true
