FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task
# Copy your function code and SQL
COPY lambda_db_seeder.py 01_create_tables.sql ./

# Install psycopg2 and any other dependencies
RUN pip install psycopg2-binary

# Set the handler
CMD ["lambda_db_seeder.handler"]