# Configuration for Unified Norm Processor

# Database configurations
databases:
  raw:
    dbname: "rawdocs"
    user: "dev"
    password: "dev"
    host: "rawdb"
    port: 5432
  
  structured:
    dbname: "structureddocs"
    user: "dev"
    password: "dev"
    host: "structureddb"
    port: 5432

# Redis configuration
redis:
  host: "redis"
  port: 6379
  db: 0

# Gemini API configuration
gemini:
  models:
    - "gemini-2.0-flash-lite"
    - "gemini-1.5-flash"
    - "gemini-2.0-flash"
    - "gemini-2.5-flash-lite"
    - "gemini-2.5-flash"
    - "gemini-1.5-pro"
    - "gemini-2.5-pro"
  
  api_keys:
    - "${GEMINI_API_KEY_1}"
    - "${GEMINI_API_KEY_2}"
    - "${GEMINI_API_KEY_3}"
    - "${GEMINI_API_KEY_4}"
  
  # Rate limiting (requests per minute per key)
  rate_limit: 5
  
  # Maximum tokens for input/output
  max_input_tokens: 1048576
  max_output_tokens: 1048576
  
  # Retry configuration
  max_retries: 3
  retry_delay: 10  # seconds
  
  # Diff threshold for model escalation (0.0 to 1.0)
  diff_threshold: 0.25

# Processing configuration
processing:
  batch_size: 1  # Start with 1 for incremental testing
  max_concurrent_requests: 1  # Start with 1 to test full pipeline
  
  # Progress tracking
  progress_report_interval: 3600  # seconds (1 hour)
  checkpoint_interval: 100  # process count
  
  # Text processing limits
  max_text_length: 500000  # characters
  min_text_length: 50      # characters

# Email configuration (optional)
email:
  enabled: false
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "${EMAIL_SENDER}"
  sender_password: "${EMAIL_PASSWORD}"
  recipient_email: "${EMAIL_RECIPIENT}"
  
  # Report frequency
  daily_report: true
  error_notifications: true

# Logging configuration
logging:
  level: "INFO"
  file: "logs/processor.log"
  max_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Error handling
error_handling:
  max_consecutive_failures: 5
  failure_cooldown: 300  # seconds (5 minutes)
  
  # Skip items that consistently fail
  max_item_retries: 3