server:
  port: 8080
  address: 0.0.0.0
  shutdown: graceful

spring:
  application:
    name: vectorial-guard
  lifecycle:
    timeout-per-shutdown-phase: 30s

logging:
  level:
    # org.springframework.web: DEBUG
    com.simpla.vectorial: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
