# Generated by Django 4.2 on 2025-08-30 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField()),
                ('text', models.TextField()),
                ('date', models.CharField(max_length=20)),
                ('source', models.URLField(max_length=500)),
                ('chunk_type', models.CharField(default='article', max_length=50)),
                ('province', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_articles', models.ManyToManyField(blank=True, to='articles.article')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField()),
                ('embedding_model', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='articles.article')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['province'], name='articles_ar_provinc_6e87a4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_number'], name='articles_ar_article_5126da_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['chunk_type'], name='articles_ar_chunk_t_4c9181_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='articles_qu_created_0ed9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['user'], name='articles_qu_user_id_d46861_idx'),
        ),
        migrations.AddIndex(
            model_name='articleembedding',
            index=models.Index(fields=['embedding_model'], name='articles_ar_embeddi_7f32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='articleembedding',
            index=models.Index(fields=['created_at'], name='articles_ar_created_e107b9_idx'),
        ),
    ]
