# Generated by Django 4.2 on 2025-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleembedding',
            name='article',
        ),
        migrations.RemoveField(
            model_name='question',
            name='related_articles',
        ),
        migrations.AddField(
            model_name='question',
            name='related_article_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleEmbedding',
        ),
    ]
