# Generated by Django 4.2 on 2025-09-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField()),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ordinal', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'divisions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='NormaStructured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoleg_id', models.IntegerField(db_index=True, unique=True)),
                ('jurisdiccion', models.CharField(blank=True, max_length=255, null=True)),
                ('clase_norma', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_norma', models.CharField(blank=True, max_length=255, null=True)),
                ('sancion', models.DateField(blank=True, null=True)),
                ('id_normas', models.JSONField(blank=True, null=True)),
                ('publicacion', models.DateField(blank=True, null=True)),
                ('titulo_sumario', models.TextField(blank=True, null=True)),
                ('titulo_resumido', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('nro_boletin', models.CharField(blank=True, max_length=255, null=True)),
                ('pag_boletin', models.CharField(blank=True, max_length=255, null=True)),
                ('texto_resumido', models.TextField(blank=True, null=True)),
                ('texto_norma', models.TextField(blank=True, null=True)),
                ('texto_norma_actualizado', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('lista_normas_que_complementa', models.JSONField(blank=True, null=True)),
                ('lista_normas_que_la_complementan', models.JSONField(blank=True, null=True)),
                ('purified_texto_norma', models.TextField(blank=True, null=True)),
                ('purified_texto_norma_actualizado', models.TextField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_source', models.CharField(blank=True, max_length=255, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_type', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_model_used', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_models_used', models.JSONField(blank=True, null=True)),
                ('llm_tokens_used', models.IntegerField(blank=True, null=True)),
                ('llm_processing_time', models.FloatField(blank=True, null=True)),
                ('llm_similarity_score', models.FloatField(blank=True, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'normas_structured',
            },
        ),
        migrations.AddIndex(
            model_name='normastructured',
            index=models.Index(fields=['infoleg_id'], name='normas_stru_infoleg_b28849_idx'),
        ),
        migrations.AddIndex(
            model_name='normastructured',
            index=models.Index(fields=['inserted_at'], name='normas_stru_inserte_aa2131_idx'),
        ),
        migrations.AddIndex(
            model_name='normastructured',
            index=models.Index(fields=['embedding_type'], name='normas_stru_embeddi_3e9903_idx'),
        ),
        migrations.AddField(
            model_name='division',
            name='norma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='chatbot.normastructured'),
        ),
        migrations.AddField(
            model_name='division',
            name='parent_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_divisions', to='chatbot.division'),
        ),
        migrations.AddField(
            model_name='article',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='chatbot.division'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_articles', to='chatbot.article'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['norma', 'order_index'], name='divisions_norma_i_50d4da_idx'),
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['parent_division'], name='divisions_parent__4e21b7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['division', 'order_index'], name='articles_divisio_3a96c2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['parent_article'], name='articles_parent__98b5fc_idx'),
        ),
    ]
