services:
  rebuilder:
    image: postgres:17
    container_name: simpla_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simpla
    ports:
      - "5450:5432"
    volumes:
      - ./norms_dump:/docker-entrypoint-initdb.d/simpla_dump.backup
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - rebuilder_postgres_data:/var/lib/postgresql/data
    networks:
      - rag-network

volumes:
  rebuilder_postgres_data:

networks:
  rag-network:
    name: simpla_data_extraction_rag-network
    external: true